/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opencv_demo_OpenCVHelper */

#ifndef _Included_com_opencv_demo_OpenCVHelper
#define _Included_com_opencv_demo_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opencv_demo_OpenCVHelper
 * Method:    ocr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_opencv_demo_OpenCVHelper_ocr
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
